[tools]
node = ['22']
python = ['system']
go = ['latest']
uv = ['latest']

[settings]
experimental = true
trusted_config_paths = [
    '~/Projects/',
    '~/projects'
]
idiomatic_version_file_enable_tools = ["node"]
